adding retry strategy for mac build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -6,6 +6,7 @@ on:
       - development
       - QA
       - main
+      - fix/bundling-issue
   pull_request:
     branches:
       - development
@@ -160,7 +161,16 @@ jobs:
         run: echo $NODE_OPTIONS
 
       - name: Install dependencies
-        run: yarn
+        run: |
+          retry_count=0
+          while ! yarn install && [ $retry_count -lt 3 ]; do
+            echo "yarn install failed, retrying..."
+            sleep 10 # Wait for 10 seconds before retrying
+            retry_count=$((retry_count + 1))
+          done
+          if [ $retry_count -eq 3 ]; then
+            exit 1 # Fail the workflow if retries are exhausted
+          fi
 
       - name: Check installed Electron version
         run: yarn why electron
